name: comcent
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  after_layout: ^1.0.7+2
  argon_buttons_flutter: ^1.0.6
  animations: ^1.1.2
  advance_pdf_viewer: ^1.2.1

  bubble_tab_indicator: ^0.1.4

  cupertino_icons: ^1.0.0
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.16.0+1
  cool_alert: ^1.0.3
  circular_profile_avatar: ^1.0.8
  chewie: ^0.12.2

  datetime_picker_formfield: ^1.0.0
  dots_indicator: ^1.2.0

  extended_image: ^1.6.0
  expandable: ^4.1.4

  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  file_picker: ^2.1.6
  flushbar: ^1.10.4
  flutter_dropdown: ^0.0.8
  flutter_easyloading: ^2.2.2
  focused_menu: ^1.0.2
  flutter_vector_icons: ^0.3.0
  flutter_linkify: ^4.0.2
  flutter_spinkit: ^4.1.2+1
  flutter_email_sender: ^4.0.0
  flutter_staggered_grid_view: ^0.3.4
  flashy_tab_bar: ^0.0.3
  flutter_native_splash: ^0.3.0

  grouped_list: ^3.7.1

  intl: ^0.16.1
  image_picker: ^0.6.7+22

  keyboard_dismisser: ^1.0.2

  provider: ^4.3.3
  percent_indicator: ^2.1.9+1

  readmore: ^1.0.1

  search_page: ^1.4.0
  speech_bubble: ^0.0.7
  smooth_page_indicator: ^0.2.0
  shared_preferences: ^0.5.12+4
  sliding_up_panel: ^1.0.2
  shimmer: ^1.1.2

  timeago: ^2.0.29

  uuid: ^2.2.2
  url_launcher: ^5.7.10

  validated: ^1.0.3
  video_thumbnail: ^0.2.5+1
  video_player: ^1.0.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/illustrations/
    - assets/splash.png